version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

issues:
  exclude-dirs:
    - vendor

linters:
  enable:
    - contextcheck
    - errname
    - errcheck
    - errorlint
    - godot
    - misspell
    - nilerr
    - tparallel
    - unparam
    - whitespace