name: Bump Homebrew formula

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'The git tag name to bump the formula to (including the "v" prefix)'
        required: true
  repository_dispatch:
    types: [update_homebrew]

permissions:
  contents: write
  actions: write

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version
        id: extract-version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "tag-name=${{ github.event.inputs.tag-name }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
            echo "tag-name=${{ github.event.client_payload.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "tag-name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Verify file path
        run: |
          echo "Listing contents of current directory"
          ls -R

      - name: Fetch SHA256 checksums
        id: fetch-sha256
        run: |
          VERSION=${{ steps.extract-version.outputs.tag-name }}
          DARWIN_AMD64_SHA256=$(curl -sL https://github.com/zscaler/zscaler-terraformer/releases/download/$VERSION/zscaler-terraformer_${VERSION}_darwin_amd64.zip | sha256sum | awk '{ print $1 }')
          DARWIN_ARM64_SHA256=$(curl -sL https://github.com/zscaler/zscaler-terraformer/releases/download/$VERSION/zscaler-terraformer_${VERSION}_darwin_arm64.zip | sha256sum | awk '{ print $1 }')
          LINUX_AMD64_SHA256=$(curl -sL https://github.com/zscaler/zscaler-terraformer/releases/download/$VERSION/zscaler-terraformer_${VERSION}_linux_amd64.zip | sha256sum | awk '{ print $1 }')
          LINUX_ARM_SHA256=$(curl -sL https://github.com/zscaler/zscaler-terraformer/releases/download/$VERSION/zscaler-terraformer_${VERSION}_linux_arm.zip | sha256sum | awk '{ print $1 }')
          LINUX_ARM64_SHA256=$(curl -sL https://github.com/zscaler/zscaler-terraformer/releases/download/$VERSION/zscaler-terraformer_${VERSION}_linux_arm64.zip | sha256sum | awk '{ print $1 }')

          echo "DARWIN_AMD64_SHA256=$DARWIN_AMD64_SHA256" >> $GITHUB_ENV
          echo "DARWIN_ARM64_SHA256=$DARWIN_ARM64_SHA256" >> $GITHUB_ENV
          echo "LINUX_AMD64_SHA256=$LINUX_AMD64_SHA256" >> $GITHUB_ENV
          echo "LINUX_ARM_SHA256=$LINUX_ARM_SHA256" >> $GITHUB_ENV
          echo "LINUX_ARM64_SHA256=$LINUX_ARM64_SHA256" >> $GITHUB_ENV

      - name: Update formula
        run: |
          VERSION=${{ steps.extract-version.outputs.tag-name }}
          DARWIN_AMD64_SHA256=${{ env.DARWIN_AMD64_SHA256 }}
          DARWIN_ARM64_SHA256=${{ env.DARWIN_ARM64_SHA256 }}
          LINUX_AMD64_SHA256=${{ env.LINUX_AMD64_SHA256 }}
          LINUX_ARM_SHA256=${{ env.LINUX_ARM_SHA256 }}
          LINUX_ARM64_SHA256=${{ env.LINUX_ARM64_SHA256 }}

          FORMULA_PATH="formula/zscaler-terraformer.rb"
          if [[ ! -f "$FORMULA_PATH" ]]; then
            FORMULA_PATH="formula/zscaler-terraformer.rb"
          fi

          sed -i "s|version \".*\"|version \"$VERSION\"|g" $FORMULA_PATH
          sed -i "s|url \".*darwin_amd64.zip\"|url \"https://github.com/zscaler/zscaler-terraformer/releases/download/$VERSION/zscaler-terraformer_${VERSION}_darwin_amd64.zip\"|g" $FORMULA_PATH
          sed -i "s|sha256 \".*\"|sha256 \"$DARWIN_AMD64_SHA256\"|g" $FORMULA_PATH

          sed -i "s|url \".*darwin_arm64.zip\"|url \"https://github.com/zscaler/zscaler-terraformer/releases/download/$VERSION/zscaler-terraformer_${VERSION}_darwin_arm64.zip\"|g" $FORMULA_PATH
          sed -i "s|sha256 \".*\"|sha256 \"$DARWIN_ARM64_SHA256\"|g" $FORMULA_PATH

          sed -i "s|url \".*linux_amd64.zip\"|url \"https://github.com/zscaler/zscaler-terraformer/releases/download/$VERSION/zscaler-terraformer_${VERSION}_linux_amd64.zip\"|g" $FORMULA_PATH
          sed -i "s|sha256 \".*\"|sha256 \"$LINUX_AMD64_SHA256\"|g" $FORMULA_PATH

          sed -i "s|url \".*linux_arm.zip\"|url \"https://github.com/zscaler/zscaler-terraformer/releases/download/$VERSION/zscaler-terraformer_${VERSION}_linux_arm.zip\"|g" $FORMULA_PATH
          sed -i "s|sha256 \".*\"|sha256 \"$LINUX_ARM_SHA256\"|g" $FORMULA_PATH

          sed -i "s|url \".*linux_arm64.zip\"|url \"https://github.com/zscaler/zscaler-terraformer/releases/download/$VERSION/zscaler-terraformer_${VERSION}_linux_arm64.zip\"|g" $FORMULA_PATH
          sed -i "s|sha256 \".*\"|sha256 \"$LINUX_ARM64_SHA256\"|g" $FORMULA_PATH

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add $FORMULA_PATH
          git commit -m "Update zscaler-terraformer formula to version $VERSION"
          git push
        env:
          COMMITTER_TOKEN: ${{ secrets.BUMP_CASK_TOKEN }}
