name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19
      - name: Build for linux/amd64
        run: go build -o zscaler-terraformer-all-linux-amd64
      - name: Build for linux/arm64
        run: GOOS=linux GOARCH=arm64 go build -o zscaler-terraformer-all-linux-arm64
      - name: Build for mac
        run: GOOS=darwin go build -o zscaler-terraformer-all-darwin-amd64
      - name: Build for mac Apple Silicon
        run: GOOS=darwin GOARCH=arm64 go build -o zscaler-terraformer-all-darwin-arm64
      - name: Build for windows
        run: GOOS=windows go build -o zscaler-terraformer-all-windows-amd64
      - name: Build for all providers
        run: go run build/multi-build/main.go

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ github.event.inputs.version }}
          prerelease: false
          files: |
            zscaler-terraformer-*