name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2.1.3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
      # - name: golint
      #   if: matrix.os != 'windows-latest'
      #   run: |
      #     go get -v -u golang.org/x/lint/golint
      #     $(go env GOPATH)/bin/golint -set_exit_status .
      - name: Download Go Dependencies
        run: go mod tidy && go mod vendor
      - name: Vet
        run: go vet ./...
      - name: setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: write ZPA Terraform configuration
        run: |
            cat > main.tf <<EOF
            terraform {
              required_providers {
                zpa = {
                  source = "zscaler/zpa"
                  version = "~> 2"
                }
              }
            }
            EOF
      - name: terraform init
        run: terraform init
      - name: zpa go test
        env:
            # ZPA_CLIENT_ID: ${{ secrets.ZPA_CLIENT_ID }}
            # ZPA_CLIENT_SECRET: ${{ secrets.ZPA_CLIENT_SECRET }}
            # ZPA_CUSTOMER_ID: ${{ secrets.ZPA_CUSTOMER_ID }}
            ZPA_CLIENT_ID: "noone@zscaler.com"
            ZPA_CLIENT_SECRET: "ZPA_CLIENT_SECRET"
            ZPA_CUSTOMER_ID: "216196257331281920"
            ZIA_USERNAME: "username"
            ZIA_PASSWORD: "password"
            ZIA_API_KEY: "ziaapikeyhere"
            ZIA_CLOUD: "zscalerthree"
            ZSCALER_TERRAFORM_INSTALL_PATH: ${{ github.workspace }}
        run: make test
